import './global.css';
import { ClientProviders } from '@/components/client-providers/providers';

export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProviders>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClientProviders>
  );
}
