import { Toaster } from 'sonner';
import { ClientProviders } from './components/providers/providers';
import './global.css';
import 'swiper/css';
import 'swiper/css/bundle';

import { OfflineAlert } from '@eshopper/ui';

export const metadata = {
  title: 'Welcome to seller-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning className="min-h-svh w-full" lang="en">
      <body className="min-h-svh w-full relative">
        <ClientProviders>
          {children}
          <Toaster />
          <OfflineAlert />
        </ClientProviders>
      </body>
    </html>
  );
}
